Repository goldami1/GraduationProject, pull requests merged in 2018-10, with the labels that each got.

#74 Phase1 <- Phase1-InSensorEventPageDev
  .vs/AgentVI/DesignTimeBuild/.dtbcache
  AgentVI/AgentVI.Android/MainActivity.cs
  AgentVI/AgentVI/AgentVI.csproj
  AgentVI/AgentVI/Converters/TimestampConverter.cs
  AgentVI/AgentVI/Interfaces/IBackButtonPressed.cs
  AgentVI/AgentVI/Interfaces/INotifyContentViewChanged.cs
  AgentVI/AgentVI/Sources/EmptyPageFiller.svg
  AgentVI/AgentVI/Sources/Icons/backButton.svg
  AgentVI/AgentVI/Utils/Settings.cs
  AgentVI/AgentVI/Utils/UpdatedContentEventArgs.cs
  AgentVI/AgentVI/ViewModels/EventDetailsViewModel.cs
  AgentVI/AgentVI/ViewModels/SensorEventsListViewModel.cs
  AgentVI/AgentVI/Views/CameraEventsPage.xaml
  AgentVI/AgentVI/Views/CameraEventsPage.xaml.cs
  AgentVI/AgentVI/Views/CamerasPage.xaml
  AgentVI/AgentVI/Views/CamerasPage.xaml.cs
  AgentVI/AgentVI/Views/EventDetailsPage.xaml
  AgentVI/AgentVI/Views/EventDetailsPage.xaml.cs
  AgentVI/AgentVI/Views/EventsPage.xaml.cs
  AgentVI/AgentVI/Views/MainPage.xaml
  AgentVI/AgentVI/Views/MainPage.xaml.cs
  AgentVI/AgentVI/Views/WaitingPagexaml.xaml
  AgentVI/AgentVI/Views/WaitingPagexaml.xaml.cs
Labels: Urgent Priority

#80 Phase1 <- Phase1-EventsFixDev
  .vs/AgentVI/DesignTimeBuild/.dtbcache
  AgentVI/AgentVI.Android/AgentVI.Android.csproj
  AgentVI/AgentVI.Android/MainActivity.cs
  AgentVI/AgentVI.iOS/AgentVI.iOS.csproj
  AgentVI/AgentVI/AgentVI.csproj
  AgentVI/AgentVI/App.xaml
  AgentVI/AgentVI/App.xaml.cs
  AgentVI/AgentVI/Converters/EnumObjectTypeSVGConverter.cs
  AgentVI/AgentVI/Interfaces/IFocusable.cs
  AgentVI/AgentVI/Interfaces/ISupportOrientation.cs
  AgentVI/AgentVI/Models/EventModel.cs
  AgentVI/AgentVI/Services/FilterService.cs
  AgentVI/AgentVI/Services/IFilterService.cs
  AgentVI/AgentVI/Sources/Icons/events_24px.svg
  AgentVI/AgentVI/Sources/Icons/events_active_24px.svg
  AgentVI/AgentVI/Sources/Icons/sensors_24px.svg
  AgentVI/AgentVI/Sources/Icons/sensors_active_24px.svg
  AgentVI/AgentVI/Sources/Icons/sensors_open.svg
  AgentVI/AgentVI/Sources/Icons/settings_24px.svg
  AgentVI/AgentVI/Sources/Icons/settings_active_24px.svg
  AgentVI/AgentVI/Sources/Icons/settings_open.svg
  AgentVI/AgentVI/Utils/Settings.cs
  AgentVI/AgentVI/Utils/StringUtils.cs
  AgentVI/AgentVI/Utils/StringValueAttribute.cs
  AgentVI/AgentVI/Utils/UpdatedContentEventArgs.cs
  AgentVI/AgentVI/ViewModels/EventDetailsViewModel.cs
  AgentVI/AgentVI/ViewModels/EventsListViewModel.cs
  AgentVI/AgentVI/ViewModels/FadingLabel.cs
  AgentVI/AgentVI/ViewModels/LandscapeEventDetailsPageVM.cs
  AgentVI/AgentVI/ViewModels/SensorEventsListViewModel.cs
  AgentVI/AgentVI/ViewModels/SensorsListViewModel.cs
  AgentVI/AgentVI/ViewModels/ViewModelLocator.cs
  AgentVI/AgentVI/Views/CameraEventsPage.xaml.cs
  AgentVI/AgentVI/Views/CamerasPage.xaml
  AgentVI/AgentVI/Views/CamerasPage.xaml.cs
  AgentVI/AgentVI/Views/EventDetailsPage.xaml
  AgentVI/AgentVI/Views/EventDetailsPage.xaml.cs
  AgentVI/AgentVI/Views/EventsPage.xaml
  AgentVI/AgentVI/Views/EventsPage.xaml.cs
  AgentVI/AgentVI/Views/LandscapeEventDetailsPage.xaml
  AgentVI/AgentVI/Views/LandscapeEventDetailsPage.xaml.cs
  AgentVI/AgentVI/Views/MainPage.xaml
  AgentVI/AgentVI/Views/MainPage.xaml.cs
Labels: FYI

#81 update
  InnoviApiProxy/SensorEvent.cs
Labels: FYI

#82 update
  InnoviApiProxy/Sensor.cs
  InnoviApiProxy/SensorEvent.cs
Labels: FYI

#83 Phase1 <- Phase1-FilteringFixesDev
  .vs/AgentVI/DesignTimeBuild/.dtbcache
  AgentVI/AgentVI/AgentVI.csproj
  AgentVI/AgentVI/Converters/tmpImagePlaceholderGeneratorConverter.cs
  AgentVI/AgentVI/Converters/tmpVidPlaceholderGeneratorConverter.cs
  AgentVI/AgentVI/Models/EventModel.cs
  AgentVI/AgentVI/Models/SensorModel.cs
  AgentVI/AgentVI/Sources/Icons/dividerIcon.svg
  AgentVI/AgentVI/Sources/Icons/folderIcon.svg
  AgentVI/AgentVI/Utils/Settings.cs
  AgentVI/AgentVI/Views/CameraEventsPage.xaml
  AgentVI/AgentVI/Views/CamerasPage.xaml
  AgentVI/AgentVI/Views/EventDetailsPage.xaml
  AgentVI/AgentVI/Views/EventDetailsPage.xaml.cs
  AgentVI/AgentVI/Views/EventsPage.xaml
  AgentVI/AgentVI/Views/FilterPage.xaml
  AgentVI/AgentVI/Views/LandscapeEventDetailsPage.xaml
  AgentVI/AgentVI/Views/MainPage.xaml
  AgentVI/AgentVI/Views/MainPage.xaml.cs
  AgentVI/AgentVI/Views/WaitingPage.xaml
  AgentVI/AgentVI/Views/WaitingPage.xaml.cs
Labels: FYI

#89 Phase1 <- Phase1-FilteringFixesDev
  .vs/AgentVI/DesignTimeBuild/.dtbcache
  AgentVI/AgentVI.Android/AgentVI.Android.csproj.user
  AgentVI/AgentVI/Utils/Settings.cs
  AgentVI/AgentVI/ViewModels/MainPageViewModel.cs
  AgentVI/AgentVI/ViewModels/MainPageViewModelExt.cs
  AgentVI/AgentVI/Views/LoadingPage.xaml.cs
  AgentVI/AgentVI/Views/MainPage.xaml
  AgentVI/AgentVI/Views/MainPage.xaml.cs
Labels: FYI

#94 Phase1 <- Phase1-FilteringFixesDev (Filter feature entirely code-redesigned)
  .vs/AgentVI/DesignTimeBuild/.dtbcache
  AgentVI/AgentVI.Android/MainActivity.cs
  AgentVI/AgentVI/AgentVI.csproj
  AgentVI/AgentVI/Services/FilterService.cs
  AgentVI/AgentVI/Services/IFilterService.cs
  AgentVI/AgentVI/Services/ILoginService.cs
  AgentVI/AgentVI/Services/IServiceModule.cs
  AgentVI/AgentVI/Services/LoginService.cs
  AgentVI/AgentVI/ViewModels/EventsListViewModel.cs
  AgentVI/AgentVI/ViewModels/FilterIndicatorViewModel.cs
  AgentVI/AgentVI/ViewModels/FilterViewModel.cs
  AgentVI/AgentVI/ViewModels/FilteringPageViewModel.cs
  AgentVI/AgentVI/ViewModels/LandscapeEventDetailsPageVM.cs
  AgentVI/AgentVI/ViewModels/LoginPageViewModel.cs
  AgentVI/AgentVI/ViewModels/MainPageViewModel.cs
  AgentVI/AgentVI/ViewModels/MainPageViewModelExt.cs
  AgentVI/AgentVI/ViewModels/SensorsListViewModel.cs
  AgentVI/AgentVI/Views/FilterPage.xaml
  AgentVI/AgentVI/Views/FilterPage.xaml.cs
  AgentVI/AgentVI/Views/LoadingPage.xaml.cs
  AgentVI/AgentVI/Views/LoginPage.xaml.cs
  AgentVI/AgentVI/Views/MainPage.xaml
  AgentVI/AgentVI/Views/MainPage.xaml.cs
Labels: FYI

#98 innoviCollection -revision
  InnoviApiProxy/Folder.cs
  InnoviApiProxy/InnoviObjectCollection.cs
  InnoviApiProxy/Sensor.cs
  NadavTest/Program.cs
Labels: bug

#99 master-dev <-Phase1-FilteringFixesDev
  .vs/AgentVI/DesignTimeBuild/.dtbcache
  AgentVI/AgentVI.Android/AgentVI.Android.csproj.user
  AgentVI/AgentVI.Android/MainActivity.cs
  AgentVI/AgentVI/AgentVI.csproj
  AgentVI/AgentVI/Converters/tmpImagePlaceholderGeneratorConverter.cs
  AgentVI/AgentVI/Models/FolderModel.cs
  AgentVI/AgentVI/Services/FilterService.cs
  AgentVI/AgentVI/Services/IFilterService.cs
  AgentVI/AgentVI/Sources/Icons/rightArrow.svg
  AgentVI/AgentVI/Utils/Settings.cs
  AgentVI/AgentVI/ViewModels/FilterIndicatorViewModel.cs
  AgentVI/AgentVI/ViewModels/FilterViewModel.cs
  AgentVI/AgentVI/ViewModels/FilteringPageViewModel.cs
  AgentVI/AgentVI/ViewModels/LandscapeEventDetailsPageVM.cs
  AgentVI/AgentVI/Views/EventDetailsPage.xaml.cs
  AgentVI/AgentVI/Views/FilterPage.xaml
  AgentVI/AgentVI/Views/FilterPage.xaml.cs
  AgentVI/AgentVI/Views/MainPage.xaml.cs
  InnoviApiProxy/InnoviObjectCollection.cs
  dir_reset.bat
Labels: FYI

#102 master-dev <- dev-AppearanceFix
  .vs/AgentVI/DesignTimeBuild/.dtbcache
  AgentVI/AgentVI.Android/AgentVI.Android.csproj
  AgentVI/AgentVI.Android/MainActivity.cs
  AgentVI/AgentVI.Android/Properties/AndroidManifest.xml
  AgentVI/AgentVI/Services/FilterService.cs
  AgentVI/AgentVI/Services/IFilterService.cs
  AgentVI/AgentVI/Utils/Settings.cs
  AgentVI/AgentVI/Views/CameraEventsPage.xaml
  AgentVI/AgentVI/Views/CamerasPage.xaml
  AgentVI/AgentVI/Views/EventDetailsPage.xaml
  AgentVI/AgentVI/Views/EventsPage.xaml
  InnoviApiProxy/InnoviObjectCollection.cs
Labels: FYI

#103 Phase1 <- master-dev
  .vs/AgentVI/DesignTimeBuild/.dtbcache
  AgentVI/AgentVI.Android/AgentVI.Android.csproj
  AgentVI/AgentVI.Android/MainActivity.cs
  AgentVI/AgentVI.Android/Properties/AndroidManifest.xml
  AgentVI/AgentVI/Services/FilterService.cs
  AgentVI/AgentVI/Services/IFilterService.cs
  AgentVI/AgentVI/Utils/Settings.cs
  AgentVI/AgentVI/Views/CameraEventsPage.xaml
  AgentVI/AgentVI/Views/CamerasPage.xaml
  AgentVI/AgentVI/Views/EventDetailsPage.xaml
  AgentVI/AgentVI/Views/EventsPage.xaml
  InnoviApiProxy/InnoviObjectCollection.cs
Labels: FYI

#104 master-dev <- dev-Appearance
  .vs/AgentVI/DesignTimeBuild/.dtbcache
  AgentVI/AgentVI.Android/AgentVI.Android.csproj
  AgentVI/AgentVI.Android/Custom/Effects/UnderlineEffect.cs
  AgentVI/AgentVI.Android/MainActivity.cs
  AgentVI/AgentVI.Android/Properties/AndroidManifest.xml
  AgentVI/AgentVI/Custom/Controls/LongRowButton.xaml
  AgentVI/AgentVI/Custom/Controls/LongRowButton.xaml.cs
  AgentVI/AgentVI/Custom/Effects/UnderlineEffect.cs
  AgentVI/AgentVI/Services/FilterService.cs
  AgentVI/AgentVI/Utils/Settings.cs
  AgentVI/AgentVI/ViewModels/FilterIndicatorViewModel.cs
  AgentVI/AgentVI/ViewModels/MainPageViewModelExt.cs
  AgentVI/AgentVI/Views/CamerasPage.xaml
  AgentVI/AgentVI/Views/EventsPage.xaml
  AgentVI/AgentVI/Views/FilterPage.xaml
  AgentVI/AgentVI/Views/MainPage.xaml
  AgentVI/AgentVI/Views/MainPage.xaml.cs
Labels: FYI

#105 Phase1 <- master-dev
  .vs/AgentVI/DesignTimeBuild/.dtbcache
  AgentVI/AgentVI.Android/AgentVI.Android.csproj
  AgentVI/AgentVI.Android/Custom/Effects/UnderlineEffect.cs
  AgentVI/AgentVI.Android/MainActivity.cs
  AgentVI/AgentVI.Android/Properties/AndroidManifest.xml
  AgentVI/AgentVI/Custom/Controls/LongRowButton.xaml
  AgentVI/AgentVI/Custom/Controls/LongRowButton.xaml.cs
  AgentVI/AgentVI/Custom/Effects/UnderlineEffect.cs
  AgentVI/AgentVI/Services/FilterService.cs
  AgentVI/AgentVI/Utils/Settings.cs
  AgentVI/AgentVI/ViewModels/FilterIndicatorViewModel.cs
  AgentVI/AgentVI/ViewModels/MainPageViewModelExt.cs
  AgentVI/AgentVI/Views/CamerasPage.xaml
  AgentVI/AgentVI/Views/EventsPage.xaml
  AgentVI/AgentVI/Views/FilterPage.xaml
  AgentVI/AgentVI/Views/MainPage.xaml
  AgentVI/AgentVI/Views/MainPage.xaml.cs
Labels: FYI

#110 upgraded performance and design
  .vs/AgentVI/DesignTimeBuild/.dtbcache
  AgentVI/AgentVI.Android/AgentVI.Android.csproj.user
  AgentVI/AgentVI.Android/MainActivity.cs
  AgentVI/AgentVI.Android/Properties/AndroidManifest.xml
  AgentVI/AgentVI/AgentVI.csproj
  AgentVI/AgentVI/Services/FilterService.cs
  AgentVI/AgentVI/Services/IFilterService.cs
  AgentVI/AgentVI/Utils/Settings.cs
  AgentVI/AgentVI/ViewModels/EventsListViewModel.cs
  AgentVI/AgentVI/ViewModels/FilterDependentViewModel.cs
  AgentVI/AgentVI/ViewModels/FilterIndicatorViewModel.cs
  AgentVI/AgentVI/ViewModels/FilterViewModel.cs
  AgentVI/AgentVI/ViewModels/FilteringPageViewModel.cs
  AgentVI/AgentVI/ViewModels/SensorEventsListViewModel.cs
  AgentVI/AgentVI/ViewModels/SensorsListViewModel.cs
  AgentVI/AgentVI/Views/EventsPage.xaml
  AgentVI/AgentVI/Views/FilterPage.xaml
  AgentVI/AgentVI/Views/FilterPage.xaml.cs
  AgentVI/AgentVI/Views/LoadingPage.xaml.cs
  AgentVI/AgentVI/Views/MainPage.xaml
  InnoviApiProxy/InnoviObjectCollection.cs
Labels: FYI

#111 master-dev <- dev-AppearanceFix
  .vs/AgentVI/DesignTimeBuild/.dtbcache
  AgentVI/AgentVI.Android/AgentVI.Android.csproj
  AgentVI/AgentVI.Android/Custom/Renderers/CustomWebViewRenderer.cs
  AgentVI/AgentVI.Android/Properties/AndroidManifest.xml
  AgentVI/AgentVI/AgentVI.csproj
  AgentVI/AgentVI/Converters/tmpVidPlaceholderGeneratorConverter.cs
  AgentVI/AgentVI/Custom/Renderers/CustomWebView.cs
  AgentVI/AgentVI/Services/FilterService.cs
  AgentVI/AgentVI/ViewModels/FilterIndicatorViewModel.cs
  AgentVI/AgentVI/ViewModels/MainPageViewModel.cs
  AgentVI/AgentVI/Views/EventDetailsPage.xaml
  AgentVI/AgentVI/Views/EventDetailsPage.xaml.cs
  AgentVI/AgentVI/Views/FilterPage.xaml.cs
  AgentVI/AgentVI/Views/MainPage.xaml
  AgentVI/AgentVI/Views/MainPage.xaml.cs
Labels: FYI

#112 master-dev <- dev-AppearanceFix
  .vs/AgentVI/DesignTimeBuild/.dtbcache
  AgentVI/AgentVI.Android/AgentVI.Android.csproj
  AgentVI/AgentVI.Android/Custom/Renderers/CustomViewCellRenderer.cs
  AgentVI/AgentVI.Android/Properties/AndroidManifest.xml
  AgentVI/AgentVI.Android/Resources/Resource.designer.cs
  AgentVI/AgentVI.Android/Resources/values/styles.xml
  AgentVI/AgentVI/AgentVI.csproj
  AgentVI/AgentVI/Custom/Controls/HeaderControl.xaml
  AgentVI/AgentVI/Custom/Controls/HeaderControl.xaml.cs
  AgentVI/AgentVI/Custom/Renderers/CustomViewCell.cs
  AgentVI/AgentVI/Utils/Settings.cs
  AgentVI/AgentVI/ViewModels/FilterViewModel.cs
  AgentVI/AgentVI/Views/CameraEventsPage.xaml
  AgentVI/AgentVI/Views/CamerasPage.xaml
  AgentVI/AgentVI/Views/CamerasPage.xaml.cs
  AgentVI/AgentVI/Views/EventsPage.xaml
  AgentVI/AgentVI/Views/EventsPage.xaml.cs
  AgentVI/AgentVI/Views/FilterPage.xaml
  AgentVI/AgentVI/Views/FilterPage.xaml.cs
  AgentVI/AgentVI/Views/MainPage.xaml
Labels: FYI

#113 update
  InnoviApiProxy/HttpUtils.cs
  InnoviApiProxy/SensorEvent.cs
  InnoviApiProxy/User.cs
Labels: FYI

#115 master-dev <- dev-AppearanceFix
  .vs/AgentVI/DesignTimeBuild/.dtbcache
  AgentVI/AgentVI.Android/MainActivity.cs
  AgentVI/AgentVI.Android/Properties/AndroidManifest.xml
  AgentVI/AgentVI/Services/FilterService.cs
  AgentVI/AgentVI/ViewModels/FilterDependentViewModel.cs
  AgentVI/AgentVI/ViewModels/LoginPageViewModel.cs
  AgentVI/AgentVI/Views/LoadingPage.xaml.cs
  AgentVI/AgentVI/Views/LoginPage.xaml
  AgentVI/AgentVI/Views/LoginPage.xaml.cs
  AgentVI/AgentVI/Views/SettingsPage.xaml.cs
Labels: FYI

#117 master-dev <- dev-AppearanceFix
  .vs/AgentVI/DesignTimeBuild/.dtbcache
  AgentVI/AgentVI.Android/AgentVI.Android.csproj
  AgentVI/AgentVI.Android/Properties/AndroidManifest.xml
  AgentVI/AgentVI/AgentVI.csproj
  AgentVI/AgentVI/Converters/tmpVidPlaceholderGeneratorConverter.cs
  AgentVI/AgentVI/Models/EventModel.cs
  AgentVI/AgentVI/Sources/Icons/events_active_24px.svg
  AgentVI/AgentVI/Sources/Icons/events_inactive_24px.svg
  AgentVI/AgentVI/Sources/Icons/health_active_24px.svg
  AgentVI/AgentVI/Sources/Icons/health_inactive_24px.svg
  AgentVI/AgentVI/Sources/Icons/sensors_active_24px.svg
  AgentVI/AgentVI/Sources/Icons/sensors_inactive_24px.svg
  AgentVI/AgentVI/Sources/Icons/settings_active_24px.svg
  AgentVI/AgentVI/Sources/Icons/settings_inactive_24px.svg
  AgentVI/AgentVI/Utils/Settings.cs
  AgentVI/AgentVI/Utils/StringUtils.cs
  AgentVI/AgentVI/ViewModels/EventDetailsViewModel.cs
  AgentVI/AgentVI/ViewModels/EventsListViewModel.cs
  AgentVI/AgentVI/ViewModels/MainPageViewModel.cs
  AgentVI/AgentVI/Views/CameraEventsPage.xaml
  AgentVI/AgentVI/Views/EventDetailsPage.xaml
  AgentVI/AgentVI/Views/EventDetailsPage.xaml.cs
  AgentVI/AgentVI/Views/EventsPage.xaml
  AgentVI/AgentVI/Views/EventsPage.xaml.cs
  AgentVI/AgentVI/Views/HealthStatPage.xaml
  AgentVI/AgentVI/Views/HealthStatPage.xaml.cs
  AgentVI/AgentVI/Views/LandscapeEventDetailsPage.xaml
  AgentVI/AgentVI/Views/MainPage.xaml
  AgentVI/AgentVI/Views/MainPage.xaml.cs
Labels: FYI

#118 master-dev <- dev-AppearanceFix
  AgentVI/AgentVI.Android/Properties/AndroidManifest.xml
  AgentVI/AgentVI/AgentVI.csproj
  AgentVI/AgentVI/Models/EventModel.cs
  AgentVI/AgentVI/Models/SensorModel.cs
  AgentVI/AgentVI/Sources/Icons/browseIcon.svg
  AgentVI/AgentVI/Sources/Icons/leftArrow.svg
  AgentVI/AgentVI/Sources/Icons/reset.svg
  AgentVI/AgentVI/Sources/Icons/rightArrow.svg
  AgentVI/AgentVI/Sources/Icons/upArrow.svg
  AgentVI/AgentVI/Utils/Settings.cs
  AgentVI/AgentVI/ViewModels/FilterDependentViewModel.cs
  AgentVI/AgentVI/ViewModels/FilterIndicatorViewModel.cs
  AgentVI/AgentVI/ViewModels/FilterViewModel.cs
  AgentVI/AgentVI/ViewModels/FilteringPageViewModel.cs
  AgentVI/AgentVI/ViewModels/SensorEventsListViewModel.cs
  AgentVI/AgentVI/Views/CameraEventsPage.xaml
  AgentVI/AgentVI/Views/CamerasPage.xaml
  AgentVI/AgentVI/Views/EventDetailsPage.xaml
  AgentVI/AgentVI/Views/EventDetailsPage.xaml.cs
  AgentVI/AgentVI/Views/EventsPage.xaml
  AgentVI/AgentVI/Views/FilterPage.xaml
  AgentVI/AgentVI/Views/FilterPage.xaml.cs
  AgentVI/AgentVI/Views/LandscapeEventDetailsPage.xaml
  AgentVI/AgentVI/Views/LandscapeEventDetailsPage.xaml.cs
  AgentVI/AgentVI/Views/MainPage.xaml
Labels: FYI

#119 Phase1 <- master-dev-dup
  .vs/AgentVI/DesignTimeBuild/.dtbcache
  AgentVI/AgentVI.Android/AgentVI.Android.csproj
  AgentVI/AgentVI.Android/Properties/AndroidManifest.xml
  AgentVI/AgentVI/AgentVI.csproj
  AgentVI/AgentVI/Converters/tmpVidPlaceholderGeneratorConverter.cs
  AgentVI/AgentVI/Models/EventModel.cs
  AgentVI/AgentVI/Models/SensorModel.cs
  AgentVI/AgentVI/Sources/Icons/browseIcon.svg
  AgentVI/AgentVI/Sources/Icons/events_active_24px.svg
  AgentVI/AgentVI/Sources/Icons/events_inactive_24px.svg
  AgentVI/AgentVI/Sources/Icons/health_active_24px.svg
  AgentVI/AgentVI/Sources/Icons/health_inactive_24px.svg
  AgentVI/AgentVI/Sources/Icons/leftArrow.svg
  AgentVI/AgentVI/Sources/Icons/reset.svg
  AgentVI/AgentVI/Sources/Icons/rightArrow.svg
  AgentVI/AgentVI/Sources/Icons/sensors_active_24px.svg
  AgentVI/AgentVI/Sources/Icons/sensors_inactive_24px.svg
  AgentVI/AgentVI/Sources/Icons/settings_active_24px.svg
  AgentVI/AgentVI/Sources/Icons/settings_inactive_24px.svg
  AgentVI/AgentVI/Sources/Icons/upArrow.svg
  AgentVI/AgentVI/Utils/Settings.cs
  AgentVI/AgentVI/Utils/StringUtils.cs
  AgentVI/AgentVI/ViewModels/EventDetailsViewModel.cs
  AgentVI/AgentVI/ViewModels/EventsListViewModel.cs
  AgentVI/AgentVI/ViewModels/FilterDependentViewModel.cs
  AgentVI/AgentVI/ViewModels/FilterIndicatorViewModel.cs
  AgentVI/AgentVI/ViewModels/FilterViewModel.cs
  AgentVI/AgentVI/ViewModels/FilteringPageViewModel.cs
  AgentVI/AgentVI/ViewModels/MainPageViewModel.cs
  AgentVI/AgentVI/ViewModels/SensorEventsListViewModel.cs
  AgentVI/AgentVI/Views/CameraEventsPage.xaml
  AgentVI/AgentVI/Views/CamerasPage.xaml
  AgentVI/AgentVI/Views/EventDetailsPage.xaml
  AgentVI/AgentVI/Views/EventDetailsPage.xaml.cs
  AgentVI/AgentVI/Views/EventsPage.xaml
  AgentVI/AgentVI/Views/EventsPage.xaml.cs
  AgentVI/AgentVI/Views/FilterPage.xaml
  AgentVI/AgentVI/Views/FilterPage.xaml.cs
  AgentVI/AgentVI/Views/HealthStatPage.xaml
  AgentVI/AgentVI/Views/HealthStatPage.xaml.cs
  AgentVI/AgentVI/Views/LandscapeEventDetailsPage.xaml
  AgentVI/AgentVI/Views/LandscapeEventDetailsPage.xaml.cs
  AgentVI/AgentVI/Views/MainPage.xaml
  AgentVI/AgentVI/Views/MainPage.xaml.cs
Labels: FYI

#120 commit
  InnoviApiProxy/Sensor.cs
  NadavTest/Program.cs
Labels: FYI, enhancement
